class Solution {
public:
   
    char findTheDifference(string s, string t) {
       unordered_map<char, int>um;
       char r;

       for(int i=0;i<t.size();i++){
        um[t[i]]++;
       }

       for(int i=0;i<s.size();i++){
        um[s[i]]--;
       }

       for(const auto& i: um){
          if(i.second==1){
            r =i.first;
          }
       }

       return r;
    }
};


/*


You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

*/